[package]
name = "searcher_txt"
version = "1.2.0"
authors = ["Raphdf201 <deschenesr545@gmail.com>"]
edition = "2021"
license-file = "unlicense.txt"
description = "A copy of grep that i mate to train my rust skills"
readme = "README.md"
homepage = "https://github.com/Raphdf201/minigrep/releases"
repository = "https://github.com/Raphdf201/minigrep"
keywords = ["cli", "grep", "search"]

[dependencies]

[profile.test]
opt-level = 1

[profile.bench]
opt-level = 2
