name: Rust builds

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.raphdf201.net/raphdf201/rust-node-image:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build release
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
